apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: kn0pzfqed-python-gitops
  description: This is GitOps manifest for kn0pzfqed-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=kn0pzfqed-python
    backstage.io/kubernetes-id: kn0pzfqed-python 
    backstage.io/techdocs-ref: dir:. 
    github.com/project-slug: rhtap-rhdh-qe/kn0pzfqed-python-gitops   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:kn0pzfqed-python
